/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.gematik.fhir.validator;

import ch.qos.logback.classic.Level;
import de.gematik.fhir.validator.sushi.SushiValidatorCommand;
import picocli.CommandLine;

@CommandLine.Command(name = "fhir-validator-cli", subcommands = SushiValidatorCommand.class)
public class App {
    @CommandLine.Mixin
    LoggingMixin loggingMixin;

    public static void main(String[] args) {
        ch.qos.logback.classic.Logger rootLogger = (ch.qos.logback.classic.Logger) org.slf4j.LoggerFactory.getLogger(ch.qos.logback.classic.Logger.ROOT_LOGGER_NAME);
        rootLogger.setLevel(Level.ERROR);

        CommandLine.IExecutionExceptionHandler errorHandler = new CommandLine.IExecutionExceptionHandler() {
            public int handleExecutionException(Exception ex,
                                                CommandLine commandLine,
                                                CommandLine.ParseResult parseResult) {
                if (!(ex instanceof ValidatorException)) {
                    ex.printStackTrace();
                }
                commandLine.getErr().println(ex.getMessage());
                return commandLine.getCommandSpec().exitCodeOnExecutionException();
            }
        };
        int exitCode = new CommandLine(new App())
                .setExecutionStrategy(LoggingMixin::executionStrategy)
                .setExecutionExceptionHandler(errorHandler)
                .execute(args);
        System.exit(exitCode);
    }

}
